name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/prototype/images/segment-2.png
    - assets/prototype/images/segment-2-4WM.png
    - assets/prototype/images/auto-group-crt5.png
    - assets/prototype/images/cover.png
    - assets/prototype/images/back.png
    - assets/prototype/images/icon.png
    - assets/prototype/images/icon-container.png
    - assets/prototype/images/auto-group-wwhx.png
    - assets/prototype/images/icon-container-gob.png
    - assets/prototype/images/icons-add24px.png
    - assets/prototype/images/segment-3.png
    - assets/prototype/images/auto-group-4mlm.png
    - assets/prototype/images/cover-wuj.png
    - assets/prototype/images/icon-6yF.png
    - assets/prototype/images/icon-gxy.png
    - assets/prototype/images/back-eu7.png
    - assets/prototype/images/state-layer.png
    - assets/prototype/images/icon-tTb.png
    - assets/prototype/images/segment-4.png
    - assets/prototype/images/media.png
    - assets/prototype/images/auto-group-gupt.png
    - assets/prototype/images/auto-group-6vqk.png
    - assets/prototype/images/media-JBb.png
    - assets/prototype/images/media-xWD.png
    - assets/prototype/images/media-GYq.png
    - assets/prototype/images/media-zEV.png
    - assets/prototype/images/leading-icon.png
    - assets/prototype/images/media-ahX.png
    - assets/prototype/images/icon-961.png
    - assets/prototype/images/icon-1db.png
    - assets/prototype/images/media-3kD.png
    - assets/prototype/images/segment-4-PiZ.png
    - assets/prototype/images/media-YNM.png
    - assets/prototype/images/media-usf.png
    - assets/prototype/images/icons-accesstime24px.png
    - assets/prototype/images/icon-7XX.png
    - assets/prototype/images/icon-5SH.png
    - assets/prototype/images/segment-3-k1F.png
    - assets/prototype/images/icon-cvu.png
    - assets/prototype/images/back-ZYM.png
    - assets/prototype/images/media-RJ9.png
    - assets/prototype/images/segment-3-gKB.png
    - assets/prototype/images/media-nzM.png
    - assets/prototype/images/heart-icon-valentine-2-1.png
    - assets/prototype/images/media-PYd.png
    - assets/prototype/images/icon-txh.png
    - assets/prototype/images/segment-2-TMT.png
    - assets/prototype/images/divider.png
    - assets/prototype/images/icon-TXf.png
    - assets/prototype/images/media-qJZ.png
    - assets/prototype/images/auto-group-mycd.png
    - assets/prototype/images/icon-container-un1.png
    - assets/prototype/images/state-layer-CdF.png
    - assets/prototype/images/media-WhX.png
    - assets/prototype/images/icon-KX7.png
    - assets/prototype/images/icon-e3b.png
    - assets/prototype/images/media-vWV.png
    - assets/prototype/images/icon-Zqb.png
    - assets/prototype/images/icon-LM7.png
    - assets/prototype/images/media-bg.png
    - assets/prototype/images/media-HHb.png
    - assets/prototype/images/media-upd.png
    - assets/prototype/images/icon-7Mj.png
    - assets/prototype/images/media-UdX.png
    - assets/prototype/images/media-6wj.png
    - assets/prototype/images/media-EiV.png
    - assets/prototype/images/segment-2-5bF.png
    - assets/prototype/images/media-bg-5Qm.png
    - assets/prototype/images/media-RJ9-mso.png
    - assets/prototype/images/icon-hmT.png
    - assets/prototype/images/icon-Zrq.png
    - assets/prototype/images/auto-group-2svp.png
    - assets/prototype/images/state-layer-xa5.png
    - assets/prototype/images/back-kPT.png
    - assets/prototype/images/leading-icon-F5K.png
    - assets/prototype/images/icon-container-mJZ.png
    - assets/prototype/images/divider-J3b.png
    - assets/prototype/images/media-ET3.png
    - assets/prototype/images/media-yQd.png
    - assets/prototype/images/media-AKs.png
    - assets/prototype/images/trailing-icon.png
    - assets/prototype/images/media-Ead.png
    - assets/prototype/images/back-hPf.png
    - assets/prototype/images/back-KUD.png
    - assets/prototype/images/media-bg-CS5.png
    - assets/prototype/images/media-bxd.png
    - assets/prototype/images/media-j3F.png
    - assets/prototype/images/segment-3-3pd.png
    - assets/prototype/images/icon-mVj.png
    - assets/prototype/images/segment-4-g6u.png
    - assets/prototype/images/media-T1B.png
    - assets/prototype/images/media-KUd.png
    - assets/prototype/images/segment-3-Ebb.png
    - assets/prototype/images/state-layer-6GR.png
    - assets/prototype/images/segment-2-q9T.png
    - assets/prototype/images/leading-icon-wiH.png
    - assets/prototype/images/auto-group-mq8y.png
    - assets/prototype/images/back-ExH.png
    - assets/prototype/images/media-Ab3.png
    - assets/prototype/images/heart-icon-valentine-2-1-3jw.png
    - assets/prototype/images/segment-4-A5o.png
    - assets/prototype/images/auto-group-p9of.png
    - assets/prototype/images/segment-4-fbX.png
    - assets/prototype/images/icon-container-MjF.png
    - assets/prototype/images/media-VaZ.png
    - assets/prototype/images/media-VXo.png
    - assets/prototype/images/media-P4m.png
    - assets/prototype/images/settings-icon.png
    - assets/prototype/images/media-cHP.png
    - assets/prototype/images/state-layer-Ra9.png
    - assets/prototype/images/icon-QtR.png
    - assets/prototype/images/media-hEZ.png
    - assets/prototype/images/segment-2-H9K.png
    - assets/prototype/images/media-TVb.png
    - assets/prototype/images/checkboxes.png
    - assets/prototype/images/segment-3-UpR.png
    - assets/prototype/images/back-9nZ.png
    - assets/prototype/images/segment-4-FYd.png
    - assets/prototype/images/media-vWd.png
    - assets/prototype/images/media-EnD.png
    - assets/prototype/images/media-Ckq.png
    - assets/prototype/images/icon-container-D3o.png
    - assets/prototype/images/media-22V.png
    - assets/assets/images/property-1default.png
    - assets/assets/images/leading-icon-Zx5.png
    - assets/assets/images/leading-icon-B4m.png
    - assets/prototype/images/media-XGM.png
    - assets/prototype/images/media-Q7B.png
    - assets/prototype/images/media-Xhb.png
    - assets/prototype/images/media-tyP.png
    - assets/prototype/images/media-2ph.png
    - assets/prototype/images/media-Fso.png
    - assets/prototype/images/media-A9X.png
    - assets/prototype/images/back-1Pf.png
    - assets/assets/images/media-Hc5.png
    - assets/assets/images/leading-icon-FQM.png
    - assets/assets/images/leading-icon-qKF.png
    - assets/prototype/images/media-CzM.png
    - assets/prototype/images/media-L4y.png
    - assets/assets/images/leading-icon-Gty.png
    - assets/prototype/images/trailing-icon-Fk5.png
    - assets/prototype/images/media-mTX.png
    - assets/prototype/images/media-NVF.png
    - assets/prototype/images/trailing-icon-wRs.png
    - assets/prototype/images/media-sqK.png
    - assets/prototype/images/media-hLV.png
    - assets/prototype/images/media-KwX.png
    - assets/prototype/images/media-pTb.png
    - assets/prototype/images/media-UVX.png
    - assets/assets/images/property-1variant2.png
    - assets/prototype/images/state-layer-tn5.png
    - assets/assets/images/segment-4-UbB.png
    - assets/assets/images/leading-icon-6XK.png
    - assets/prototype/images/media-FgD.png
    - assets/assets/images/media-ye1.png
    - assets/assets/images/checkboxes-meH.png
    - assets/assets/images/divider-dww.png
    - assets/assets/images/st-trailing-icon.png
    - assets/assets/images/leading-icon-tKB.png
    - assets/assets/images/checkboxes-z7K.png
    - assets/assets/images/media-W4y.png
    - assets/assets/images/heart-icon-valentine-2-1-GqP.png
    - assets/assets/images/checkboxes-ePs.png
    - assets/assets/images/icon-kho.png
    - assets/assets/images/checkboxes-tZ7.png
    - assets/assets/images/checkboxes-EN5.png
    - assets/assets/images/icon-container-TEq.png
    - assets/assets/images/checkboxes-CCR.png
    - assets/assets/images/segment-2-XkV.png
    - assets/assets/images/state-layer-ZhB.png
    - assets/assets/images/st-trailing-icon-X1j.png
    - assets/assets/images/checkboxes-41f.png
    - assets/assets/images/checkboxes-b1b.png
    - assets/assets/images/st-trailing-icon-pf3.png
    - assets/assets/images/media-DVj.png
    - assets/assets/images/media-oi9.png
    - assets/assets/images/auto-group-hift.png
    - assets/assets/images/checkboxes-VGm.png
    - assets/assets/images/icon-LYH.png
    - assets/assets/images/ic-round-camera-alt.png
    - assets/assets/images/checkboxes-ckh.png
    - assets/assets/images/checkboxes-swX.png
    - assets/assets/images/media-YPs.png
    - assets/assets/images/leading-icon-KP7.png
    - assets/assets/images/segment-3-Kb7.png
    - assets/assets/images/leading-icon-Tcm.png
    - assets/assets/images/checkboxes-v7j.png
    - assets/assets/images/checkboxes-oxD.png
    - assets/assets/images/checkboxes-YQ1.png
    - assets/assets/images/media-61X.png
    - assets/assets/images/heart-icon-valentine-2-1-DRs.png
    - assets/assets/images/heart-icon-valentine-2-1-iX3.png
    - assets/assets/images/media-9nR.png
    - assets/assets/images/heart-icon-valentine-2-1-i9o.png
    - assets/assets/images/auto-group-ofxp.png
    - assets/assets/images/property-1default-RXo.png
    - assets/assets/images/heart-icon-valentine-2-1-FL5.png
    - assets/assets/images/heart-icon-valentine-2-1-sp5.png
    - assets/assets/images/heart-icon-valentine-2-1-kos.png
    - assets/assets/images/heart-icon-valentine-2-1-XX7.png
    - assets/assets/images/heart-icon-valentine-2-1-84q.png
    - assets/assets/images/heart-icon-valentine-2-1-Ttu.png
    - assets/assets/images/heart-icon-valentine-2-1-SBb.png
    - assets/assets/images/heart-icon-valentine-2-1-Vub.png
    - assets/assets/images/heart-icon-valentine-2-1-a4R.png
    - assets/covers/images/harrypotter.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
